### ISSUE TITLE
The plug-in is not compatible with the latest version of NV da.

### ISSUE THREAD

**Issue by anmi2004** [Brynify/Unspoken#4]
I hope you can adapt to the latest version of the software. And fix the abnormal sound after using the plug-in for a long time.The problem occurs as long as the reverb function in the settings is turned on.

**Comment by Brynify** [comment]
Hi there! I do plan to eventually sit down and see if I can figure out why the plugin isn't working in 2023.1. As for the reverb issue, I believe this is a Synthizer problem.

**Comment by Brynify** [comment]
Hi there,

Sorry for the long wait, I forgot to update this add-on. I've done so now, check the releases page.
