### ISSUE TITLE
Hopefully developers will submit plugins to the store

### ISSUE THREAD

**Issue by anmi2004** [Brynify/Unspoken#7]
Greetings esteemed developer. This plugin you have developed is excellent and enjoyable. I hope you will submit this plugin to the plugin store so that many people can easily access such an excellent plugin!

There are still a lot of people in the Chinese community using the previous version which has been discontinued. One of the maintainers is working on a compatibility update, but it doesn't fix the bugs, so there are still a lot of problems!

I hope this great plugin will still be available in 2024.1. Also I would like to provide a Chinese translation of the plugin, but there is a lot I don't know about the development side of things

Really thank you for still doing this plugin update maintenance, sincerely wish you work well, good health!

**Comment by Brynify** [comment]
Hi there, I do not plan to update this plugin any further due to bugs with Synthizer that are not going to be fixed. Sorry about that.
